# Catppuccin Mocha
# https://github.com/catppuccin/catppuccin

background      = #1e1e2eee
text            = #cdd6f4
accent          = #fab387
button_inactive = #313244
slider_inactive = #6c708659
handle          = #cdd6f4
