# Gruvbox Dark
# https://github.com/morhetz/gruvbox

background      = #282828ee
text            = #ebdbb2
accent          = #fe8019
button_inactive = #504945
slider_inactive = #665c5459
handle          = #ebdbb2
