# Tokyo Night
# https://github.com/enkia/tokyo-night-vscode-theme

background      = #1a1b2eee
text            = #a9b1d6
accent          = #7aa2f7
button_inactive = #24283b
slider_inactive = #565f8959
handle          = #a9b1d6
